function formatNumber(numero){if(numero<10)numero="0"+numero;return numero;}
function mostrarocultar(id){var c=document.getElementById('texto'+id);var l=document.getElementById('label'+id);if(c.style.display=='none'){c.style.display='block';l.innerHTML="Ocultar";}else{c.style.display='none';l.innerHTML="Mostrar";}
return false;}
function publicarcomentario(boton,id){var caja=document.formularioComentarios.comentario;if(caja.value.length<10){alert('Debes escribir al menos 10 caracteres.');return false;}
if(caja.value.length>255){alert('El comentario no puede superar los 255 caracteres. Te invitamos a crear un tema en nuestro foro (foro.tdslegacy.com).');return false;}
caja.disabled=true;boton.disabled=true;boton.value='Añadiendo Comentario...';var ajax;try{ajax=new ActiveXObject("Microsoft.XMLHTTP");}catch(expeption){ajax=new XMLHttpRequest();}
ajax.open("POST","comentarios/control.php",true);ajax.setRequestHeader("Content-Type","application/x-www-form-urlencoded");ajax.send("agregar="+encodeURIComponent(caja.value)+"&id="+id);ajax.onreadystatechange=function(){if(ajax.readyState==4){boton.value='Comentario Añadido';procesar_respuesta(ajax.responseText,id);}}
return false;}
function borrarcomentario(id){var ajax;var resultado;var texto;try{ajax=new ActiveXObject("Microsoft.XMLHTTP");}catch(expeption){ajax=new XMLHttpRequest();}
ajax.open("POST","comentarios/control.php",true);ajax.setRequestHeader("Content-Type","application/x-www-form-urlencoded");ajax.send("eliminar="+id);ajax.onreadystatechange=function(){if(ajax.readyState==4){procesar_respuesta(ajax.responseText,id);}}
return false;}
function votar_comentario(voto,id){var ajax;try{ajax=new ActiveXObject("Microsoft.XMLHTTP");}catch(expeption){ajax=new XMLHttpRequest();}
ajax.open("POST","comentarios/control.php",true);ajax.setRequestHeader("Content-Type","application/x-www-form-urlencoded");ajax.send("votar="+voto+"&id="+id);ajax.onreadystatechange=function(){if(ajax.readyState==4){if(ajax.responseText!=''){procesar_respuesta(ajax.responseText,id);}}}
return false;}
function reportar_com(id){var ajax;try{ajax=new ActiveXObject("Microsoft.XMLHTTP");}catch(expeption){ajax=new XMLHttpRequest();}
ajax.open("POST","comentarios/control.php",true);ajax.setRequestHeader("Content-Type","application/x-www-form-urlencoded");ajax.send("reportar="+id);ajax.onreadystatechange=function(){if(ajax.readyState==4){if(ajax.responseText!=''){procesar_respuesta(ajax.responseText,id);}}}
return false;}
function procesar_respuesta(respuesta,id){var resultado=respuesta.split("<|>");var r_int=parseInt(resultado[0]);if(r_int!=52){var texto_box=document.getElementById('texto'+id);var val_box=document.getElementById('vot'+id);var re_box=document.getElementById('result'+id);}else{var texto_box=document.getElementById('texto_coment');var re_box=document.getElementById('ncomentario');var val_box=document.getElementById('vtb0');}
switch(r_int){case 4:re_box.innerHTML="<b style='color:green;'>Comentario moderado.</b>";texto_box.innerHTML="<strong><em>El comentario fue eliminado por un moderador.</em></strong>";break;case 8:re_box.innerHTML="Comentario censurado.";texto_box.innerHTML="<strong><em>El comentario fue censurado por el creador del contenido.</em></strong>";break;case 16:re_box.innerHTML="<span style='color:red;'>Comentario eliminado</b>";texto_box.innerHTML="<strong><em>El comentario fue eliminado por su creador.</em></strong>";break;case 32:re_box.innerHTML="<b style='color:green;'>El mensaje fue reportado. Gracias.</b>";break;case 11:case 13:alert("El comentario no existe.");break;case 50:re_box.innerHTML="<b style='color:green;'>Voto computado.</b>";val_box.innerHTML=resultado[1];break;case 51:re_box.innerHTML="<b style='color:red;'>Ya votaste este comentario.</b>";val_box.innerHTML=resultado[1];break;case 49:re_box.innerHTML="<b style='color:red;'>No podes votarte a ti mismo.</b>";break;case 52:re_box.style.display='inline';texto_box.innerHTML=resultado[1];texto_box.style.display='inline';val_box.style.display='none';break;case 12:alert("Su cuenta premium no esta habilitada para comentar.");break;case 10:case 210:re_box.innerHTML="<b style='color:red;'>Para votar necesitas <a href='/cuenta-premium.php'>ingresar</a> en tu cuenta premium.</b>";break;case 211:re_box.innerHTML="<b style='color:red;'>Tu cuenta esta vencida, necesitas <a href='/cpremium.php?a=adquirirtiempo'>cargar</a> tiempo premium.";break;default:alert(respuesta);break;}}